# Development-specific overrides
services:
  postgres:
    environment:
      POSTGRES_DB: ai_agent_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dev_password
    ports:
      - "5433:5432" # Different port to avoid conflicts
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./src/ai_agent/infrastructure/database/migrations:/docker-entrypoint-initdb.d

  redis:
    ports:
      - "6380:6379" # Different port to avoid conflicts
    volumes:
      - redis_dev_data:/data

volumes:
  postgres_dev_data:
    driver: local
  redis_dev_data:
    driver: local
